### ISSUE TITLE
Trouble with imports and data.txt missing

### ISSUE THREAD

**Issue by JaimePSantos** [den01-python-programming-exercises/exercise-4-28-storing-records-JaimePSantos#1]
Hello,
I am getting some errors from importing Person, importing the exercise in the test file and the data.txt file is missing. 
Local tests work fine, but when i change the import to `from src.person import...` i get the error:
`E         At index 0 diff: <src.person.Person object at 0x7f47729070a0> != 'lily'`
Perhaps it's the command os.chdir not working properly.
Thanks!

**Comment by Scott3142** [comment]
There's probably a couple of things here. Take a look at the `if __name__ == '__main__':` statement if you're having trouble with imports. You'll probably need something like this:

```
if __name__ == '__main__':
    from person import Person
    main()
else:
    from src.person import Person
```

But there's something else wrong with your code - take a look at what the method `read_records_from_file` is supposed to return. It's not supposed to return a list of `Person` methods, just a list containing the _names_ of the people in the file.

**Comment by JaimePSantos** [comment]
That fixed it, thank you very much! I did have to move the exercise import in the test file before the function definition, github was having issues with it.
